services:
  mongo:
    image: mongo:6
    container_name: mongodb_container
    ports:
      - "27017:27017"

  server:
    build: ./server
    container_name: node_backend
    ports:
      - "5001:5001"
    environment:
      MONGO_URI: mongodb://mongo:27017/taskdb
      PORT: 5001
      JWT_SECRET: mysecret
    depends_on:
      - mongo

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server