name: Node CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: install dependencies
        run: npm install

      - name: run eslint
        run: npx eslint .

      - name: run tests
        run: npm test